// export const GET_PARTICIPANTSLIST = 'GET_PARTICIPANTSLIST'
export const SET_ROULEID = 'SET_ROULEID';
export const SET_BASICINFOFORM= 'SET_BASICINFOFORM';
export const SET_INDEXCURRENTDATE= 'SET_INDEXCURRENTDATE';//薪资核算首页选择时间


