export const SHOWAPP = 'SHOWAPP'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_PRIVILIGEVOLiST = 'SET_PRIVILIGEVOLiST'
export const SET_TAXSUBJECTINFOLIST = 'SET_TAXSUBJECTINFOLIST'
export const SET_COUNTRYLIST = 'SET_COUNTRYLIST'
export const SET_BANKLIST = 'SET_BANKLIST'
export const SET_CITYLIST = 'SET_CITYLIST'

